{
    "code": 200,
    "content": [],
    "title": "record 567322d09f9d5113c3a63dea comments list"
}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>NameError: global name 'resource' is not defined // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does not by
         accident trigger a request to /favicon.ico which might change the application
         state. -->
    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 139995331998736,
          CONSOLE_MODE = false,
          EVALEX = true,
          SECRET = "7VlrYDPxlygemui8sX1M";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>NameError</h1>
<div class="detail">
  <p class="errormsg">NameError: global name 'resource' is not defined</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  
  <ul><li><div class="frame" id="frame-139995331997776">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1836</em>,
      in <code class="function">__call__</code></h4>
  <pre>return self.wsgi_app(environ, start_response)</pre>
</div>

<li><div class="frame" id="frame-139995331998480">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1820</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.make_response(self.handle_exception(e))</pre>
</div>

<li><div class="frame" id="frame-139995331998864">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1403</em>,
      in <code class="function">handle_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-139995331998800">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1817</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.full_dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-139995331998544">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1477</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.handle_user_exception(e)</pre>
</div>

<li><div class="frame" id="frame-139995331998608">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1381</em>,
      in <code class="function">handle_user_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-139995331999056">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1475</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-139995331998992">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1461</em>,
      in <code class="function">dispatch_request</code></h4>
  <pre>return self.view_functions[rule.endpoint](**req.view_args)</pre>
</div>

<li><div class="frame" id="frame-139995331999312">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py"</cite>,
      line <em class="line">637</em>,
      in <code class="function">wrapped_function</code></h4>
  <pre>resp = fk.make_response(f(*args, **kwargs))</pre>
</div>

<li><div class="frame" id="frame-139995331998672">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py"</cite>,
      line <em class="line">180</em>,
      in <code class="function">admin_comment_send</code></h4>
  <pre>return api_response(200, 'Comment delivered', comment.info())</pre>
</div>

<li><div class="frame" id="frame-139995331999440">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-db/corrdb/common/models/comment_model.py"</cite>,
      line <em class="line">44</em>,
      in <code class="function">info</code></h4>
  <pre>if resource != None:</pre>
</div>
</ul>
  <blockquote>NameError: global name 'resource' is not defined</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 180, in admin_comment_send
    return api_response(200, 'Comment delivered', comment.info())
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-db/corrdb/common/models/comment_model.py", line 44, in info
    if resource != None:
NameError: global name 'resource' is not defined</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 180, in admin_comment_send
    return api_response(200, 'Comment delivered', comment.info())
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-db/corrdb/common/models/comment_model.py", line 44, in info
    if resource != None:
NameError: global name 'resource' is not defined

-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>NameError: global name 'resource' is not defined // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does not by
         accident trigger a request to /favicon.ico which might change the application
         state. -->
    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 139995261294608,
          CONSOLE_MODE = false,
          EVALEX = true,
          SECRET = "7VlrYDPxlygemui8sX1M";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>NameError</h1>
<div class="detail">
  <p class="errormsg">NameError: global name 'resource' is not defined</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  
  <ul><li><div class="frame" id="frame-139995261295056">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1836</em>,
      in <code class="function">__call__</code></h4>
  <pre>return self.wsgi_app(environ, start_response)</pre>
</div>

<li><div class="frame" id="frame-139995261295120">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1820</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.make_response(self.handle_exception(e))</pre>
</div>

<li><div class="frame" id="frame-139995261294928">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1403</em>,
      in <code class="function">handle_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-139995261295312">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1817</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.full_dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-139995261295440">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1477</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.handle_user_exception(e)</pre>
</div>

<li><div class="frame" id="frame-139995261295376">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1381</em>,
      in <code class="function">handle_user_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-139995261295248">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1475</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-139995261295184">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1461</em>,
      in <code class="function">dispatch_request</code></h4>
  <pre>return self.view_functions[rule.endpoint](**req.view_args)</pre>
</div>

<li><div class="frame" id="frame-139995261295632">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py"</cite>,
      line <em class="line">637</em>,
      in <code class="function">wrapped_function</code></h4>
  <pre>resp = fk.make_response(f(*args, **kwargs))</pre>
</div>

<li><div class="frame" id="frame-139995261294992">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py"</cite>,
      line <em class="line">180</em>,
      in <code class="function">admin_comment_send</code></h4>
  <pre>return api_response(200, 'Comment delivered', comment.info())</pre>
</div>

<li><div class="frame" id="frame-139995261296080">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-db/corrdb/common/models/comment_model.py"</cite>,
      line <em class="line">44</em>,
      in <code class="function">info</code></h4>
  <pre>if resource != None:</pre>
</div>
</ul>
  <blockquote>NameError: global name 'resource' is not defined</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 180, in admin_comment_send
    return api_response(200, 'Comment delivered', comment.info())
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-db/corrdb/common/models/comment_model.py", line 44, in info
    if resource != None:
NameError: global name 'resource' is not defined</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 180, in admin_comment_send
    return api_response(200, 'Comment delivered', comment.info())
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-db/corrdb/common/models/comment_model.py", line 44, in info
    if resource != None:
NameError: global name 'resource' is not defined

-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>NameError: global name 'resource' is not defined // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does not by
         accident trigger a request to /favicon.ico which might change the application
         state. -->
    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 139995259678480,
          CONSOLE_MODE = false,
          EVALEX = true,
          SECRET = "7VlrYDPxlygemui8sX1M";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>NameError</h1>
<div class="detail">
  <p class="errormsg">NameError: global name 'resource' is not defined</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  
  <ul><li><div class="frame" id="frame-139995259678672">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1836</em>,
      in <code class="function">__call__</code></h4>
  <pre>return self.wsgi_app(environ, start_response)</pre>
</div>

<li><div class="frame" id="frame-139995256221776">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1820</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.make_response(self.handle_exception(e))</pre>
</div>

<li><div class="frame" id="frame-139995256221840">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1403</em>,
      in <code class="function">handle_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-139995256222096">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1817</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.full_dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-139995256222224">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1477</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.handle_user_exception(e)</pre>
</div>

<li><div class="frame" id="frame-139995256222160">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1381</em>,
      in <code class="function">handle_user_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-139995256222032">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1475</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-139995256221968">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1461</em>,
      in <code class="function">dispatch_request</code></h4>
  <pre>return self.view_functions[rule.endpoint](**req.view_args)</pre>
</div>

<li><div class="frame" id="frame-139995256222416">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py"</cite>,
      line <em class="line">637</em>,
      in <code class="function">wrapped_function</code></h4>
  <pre>resp = fk.make_response(f(*args, **kwargs))</pre>
</div>

<li><div class="frame" id="frame-139995256221904">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py"</cite>,
      line <em class="line">180</em>,
      in <code class="function">admin_comment_send</code></h4>
  <pre>return api_response(200, 'Comment delivered', comment.info())</pre>
</div>

<li><div class="frame" id="frame-139995256222864">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-db/corrdb/common/models/comment_model.py"</cite>,
      line <em class="line">44</em>,
      in <code class="function">info</code></h4>
  <pre>if resource != None:</pre>
</div>
</ul>
  <blockquote>NameError: global name 'resource' is not defined</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 180, in admin_comment_send
    return api_response(200, 'Comment delivered', comment.info())
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-db/corrdb/common/models/comment_model.py", line 44, in info
    if resource != None:
NameError: global name 'resource' is not defined</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 180, in admin_comment_send
    return api_response(200, 'Comment delivered', comment.info())
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-db/corrdb/common/models/comment_model.py", line 44, in info
    if resource != None:
NameError: global name 'resource' is not defined

-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>AttributeError: 'unicode' object has no attribute 'extended' // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does not by
         accident trigger a request to /favicon.ico which might change the application
         state. -->
    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 139995252790608,
          CONSOLE_MODE = false,
          EVALEX = true,
          SECRET = "7VlrYDPxlygemui8sX1M";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>AttributeError</h1>
<div class="detail">
  <p class="errormsg">AttributeError: 'unicode' object has no attribute 'extended'</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  
  <ul><li><div class="frame" id="frame-139995252790288">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1836</em>,
      in <code class="function">__call__</code></h4>
  <pre>return self.wsgi_app(environ, start_response)</pre>
</div>

<li><div class="frame" id="frame-139995252790544">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1820</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.make_response(self.handle_exception(e))</pre>
</div>

<li><div class="frame" id="frame-139995252790480">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1403</em>,
      in <code class="function">handle_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-139995252790864">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1817</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.full_dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-139995252790736">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1477</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.handle_user_exception(e)</pre>
</div>

<li><div class="frame" id="frame-139995252790928">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1381</em>,
      in <code class="function">handle_user_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-139995252790800">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1475</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-139995252791120">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1461</em>,
      in <code class="function">dispatch_request</code></h4>
  <pre>return self.view_functions[rule.endpoint](**req.view_args)</pre>
</div>

<li><div class="frame" id="frame-139995252791056">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py"</cite>,
      line <em class="line">637</em>,
      in <code class="function">wrapped_function</code></h4>
  <pre>resp = fk.make_response(f(*args, **kwargs))</pre>
</div>

<li><div class="frame" id="frame-139995252790672">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py"</cite>,
      line <em class="line">209</em>,
      in <code class="function">admin_comment_all</code></h4>
  <pre>comments = [comment.extended() for comment in item.comments]</pre>
</div>
</ul>
  <blockquote>AttributeError: 'unicode' object has no attribute 'extended'</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 209, in admin_comment_all
    comments = [comment.extended() for comment in item.comments]
AttributeError: 'unicode' object has no attribute 'extended'</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 209, in admin_comment_all
    comments = [comment.extended() for comment in item.comments]
AttributeError: 'unicode' object has no attribute 'extended'

-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>NameError: global name 'resource' is not defined // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does not by
         accident trigger a request to /favicon.ico which might change the application
         state. -->
    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 139664190433616,
          CONSOLE_MODE = false,
          EVALEX = true,
          SECRET = "DqDQ7vXwHvIhm7arJ0F5";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>NameError</h1>
<div class="detail">
  <p class="errormsg">NameError: global name 'resource' is not defined</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  
  <ul><li><div class="frame" id="frame-139664190433168">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1836</em>,
      in <code class="function">__call__</code></h4>
  <pre>return self.wsgi_app(environ, start_response)</pre>
</div>

<li><div class="frame" id="frame-139664190433552">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1820</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.make_response(self.handle_exception(e))</pre>
</div>

<li><div class="frame" id="frame-139664190433808">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1403</em>,
      in <code class="function">handle_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-139664190433680">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1817</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.full_dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-139664190432272">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1477</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.handle_user_exception(e)</pre>
</div>

<li><div class="frame" id="frame-139664190432208">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1381</em>,
      in <code class="function">handle_user_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-139664190431760">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1475</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-139664190433744">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1461</em>,
      in <code class="function">dispatch_request</code></h4>
  <pre>return self.view_functions[rule.endpoint](**req.view_args)</pre>
</div>

<li><div class="frame" id="frame-139664190434000">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py"</cite>,
      line <em class="line">637</em>,
      in <code class="function">wrapped_function</code></h4>
  <pre>resp = fk.make_response(f(*args, **kwargs))</pre>
</div>

<li><div class="frame" id="frame-139664190433488">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py"</cite>,
      line <em class="line">209</em>,
      in <code class="function">admin_comment_all</code></h4>
  <pre>comments = [comment.extended() for comment in item._comments()]</pre>
</div>

<li><div class="frame" id="frame-139664190434768">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-db/corrdb/common/models/comment_model.py"</cite>,
      line <em class="line">51</em>,
      in <code class="function">extended</code></h4>
  <pre>data = self.info()</pre>
</div>

<li><div class="frame" id="frame-139664190433936">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-db/corrdb/common/models/comment_model.py"</cite>,
      line <em class="line">44</em>,
      in <code class="function">info</code></h4>
  <pre>if resource != None:</pre>
</div>
</ul>
  <blockquote>NameError: global name 'resource' is not defined</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 209, in admin_comment_all
    comments = [comment.extended() for comment in item._comments()]
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-db/corrdb/common/models/comment_model.py", line 51, in extended
    data = self.info()
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-db/corrdb/common/models/comment_model.py", line 44, in info
    if resource != None:
NameError: global name 'resource' is not defined</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 209, in admin_comment_all
    comments = [comment.extended() for comment in item._comments()]
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-db/corrdb/common/models/comment_model.py", line 51, in extended
    data = self.info()
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-db/corrdb/common/models/comment_model.py", line 44, in info
    if resource != None:
NameError: global name 'resource' is not defined

-->

{
    "code": 200,
    "content": [
        {
            "attachments": [],
            "content": "What do you think about my comment user1?",
            "created": "2015-12-17 21:05:26.781000",
            "extend": {},
            "id": "567323969f9d5114393d0caa",
            "sender": "56731c3a9f9d5110105a27f4",
            "title": "This is a simple comment from user2 on the record",
            "useful": []
        },
        {
            "attachments": [],
            "content": "Ask me something interesting user2.",
            "created": "2015-12-17 21:05:26.795000",
            "extend": {},
            "id": "567323969f9d5114393d0cad",
            "sender": "56731c3a9f9d5110105a27f1",
            "title": "This is a simple comment to user2 on the record",
            "useful": []
        },
        {
            "attachments": [],
            "content": "User1, Can we do some phase field simulations with PyMKS?",
            "created": "2015-12-17 21:05:26.808000",
            "extend": {},
            "id": "567323969f9d5114393d0cb0",
            "sender": "56731c3a9f9d5110105a27f4",
            "title": "This is now a comment on the MKS project",
            "useful": []
        }
    ],
    "title": "record 567322d09f9d5113c3a63dea comments list"
}
