{
    "code": 201,
    "content": {
        "attachments": 0,
        "created": "2015-12-17 21:19:06.098349",
        "id": "567326ca9f9d5114f35257e1",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Hello User2"
    },
    "title": "Message created"
}
{
    "code": 201,
    "content": {
        "attachments": 0,
        "created": "2015-12-17 21:19:06.104415",
        "id": "567326ca9f9d5114f35257e4",
        "receiver": "56731c3a9f9d5110105a27f1",
        "sender": "56731c3a9f9d5110105a27f4",
        "title": "Duplicated - Re - Hello User2"
    },
    "title": "Message created"
}
{
    "code": 201,
    "content": {
        "attachments": 0,
        "created": "2015-12-17 21:19:06.110376",
        "id": "567326ca9f9d5114f35257e7",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Test message"
    },
    "title": "Message created"
}
{
    "code": 200,
    "content": {
        "messages": [
            {
                "attachments": [],
                "content": "It is user 1 and i was wondering if you had any record on some DFT simulations.Thanks, User1",
                "created": "2015-12-17 21:19:06.098000",
                "extend": {},
                "id": "567326ca9f9d5114f35257e1",
                "receiver": "56731c3a9f9d5110105a27f4",
                "sender": "56731c3a9f9d5110105a27f1",
                "title": "Duplicated - Hello User2"
            },
            {
                "attachments": [],
                "content": "Hi user1, I am sorry but i currently do not have any exemple with some DFT simulations. Are you interested into collaborating in one? Thank you, User2",
                "created": "2015-12-17 21:19:06.104000",
                "extend": {},
                "id": "567326ca9f9d5114f35257e4",
                "receiver": "56731c3a9f9d5110105a27f1",
                "sender": "56731c3a9f9d5110105a27f4",
                "title": "Duplicated - Re - Hello User2"
            },
            {
                "attachments": [],
                "content": "This is just a test message from user2.",
                "created": "2015-12-17 21:19:06.110000",
                "extend": {},
                "id": "567326ca9f9d5114f35257e7",
                "receiver": "56731c3a9f9d5110105a27f4",
                "sender": "56731c3a9f9d5110105a27f1",
                "title": "Duplicated - Test message"
            }
        ],
        "total_messages": 3
    },
    "title": "Messages list"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "It is user 1 and i was wondering if you had any record on some DFT simulations.Thanks, User1",
        "created": "2015-12-17 21:19:06.098000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e1",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Hello User2"
    },
    "title": "Message 567326ca9f9d5114f35257e1"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "Hi user1, I am sorry but i currently do not have any exemple with some DFT simulations. Are you interested into collaborating in one? Thank you, User2",
        "created": "2015-12-17 21:19:06.104000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e4",
        "receiver": "56731c3a9f9d5110105a27f1",
        "sender": "56731c3a9f9d5110105a27f4",
        "title": "Duplicated - Re - Hello User2"
    },
    "title": "Message 567326ca9f9d5114f35257e4"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "This is just a test message from user2.",
        "created": "2015-12-17 21:19:06.110000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e7",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Test message"
    },
    "title": "Message 567326ca9f9d5114f35257e7"
}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>UnboundLocalError: local variable 'project_id' referenced before assignment // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does not by
         accident trigger a request to /favicon.ico which might change the application
         state. -->
    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 139834556033872,
          CONSOLE_MODE = false,
          EVALEX = true,
          SECRET = "BgFIrbgfBvnVmR4716ks";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>UnboundLocalError</h1>
<div class="detail">
  <p class="errormsg">UnboundLocalError: local variable 'project_id' referenced before assignment</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  
  <ul><li><div class="frame" id="frame-139834556033424">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1836</em>,
      in <code class="function">__call__</code></h4>
  <pre>return self.wsgi_app(environ, start_response)</pre>
</div>

<li><div class="frame" id="frame-139834556032336">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1820</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.make_response(self.handle_exception(e))</pre>
</div>

<li><div class="frame" id="frame-139834556032464">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1403</em>,
      in <code class="function">handle_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-139834556032400">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1817</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.full_dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-139834556033104">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1477</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.handle_user_exception(e)</pre>
</div>

<li><div class="frame" id="frame-139834556032144">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1381</em>,
      in <code class="function">handle_user_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-139834556031952">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1475</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-139834556032272">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1461</em>,
      in <code class="function">dispatch_request</code></h4>
  <pre>return self.view_functions[rule.endpoint](**req.view_args)</pre>
</div>

<li><div class="frame" id="frame-139834556033168">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py"</cite>,
      line <em class="line">637</em>,
      in <code class="function">wrapped_function</code></h4>
  <pre>resp = fk.make_response(f(*args, **kwargs))</pre>
</div>

<li><div class="frame" id="frame-139834556032848">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py"</cite>,
      line <em class="line">1623</em>,
      in <code class="function">admin_record_update</code></h4>
  <pre>record = RecordModel.objects.with_id(project_id)</pre>
</div>
</ul>
  <blockquote>UnboundLocalError: local variable 'project_id' referenced before assignment</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 1623, in admin_record_update
    record = RecordModel.objects.with_id(project_id)
UnboundLocalError: local variable 'project_id' referenced before assignment</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 1623, in admin_record_update
    record = RecordModel.objects.with_id(project_id)
UnboundLocalError: local variable 'project_id' referenced before assignment

-->

{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "This is just a test message from user2.",
        "created": "2015-12-17 21:19:06.110000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e7",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Test message"
    },
    "title": "Message 567326ca9f9d5114f35257e7"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "It is user 1 and i was wondering if you had any record on some DFT simulations.Thanks, User1",
        "created": "2015-12-17 21:19:06.098000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e1",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Hello User2"
    },
    "title": "Message 567326ca9f9d5114f35257e1"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "Hi user1, I am sorry but i currently do not have any exemple with some DFT simulations. Are you interested into collaborating in one? Thank you, User2",
        "created": "2015-12-17 21:19:06.104000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e4",
        "receiver": "56731c3a9f9d5110105a27f1",
        "sender": "56731c3a9f9d5110105a27f4",
        "title": "Duplicated - Re - Hello User2"
    },
    "title": "Message 567326ca9f9d5114f35257e4"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "This is just a test message from user2.",
        "created": "2015-12-17 21:19:06.110000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e7",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Test message"
    },
    "title": "Message 567326ca9f9d5114f35257e7"
}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>NameError: global name 'app_id' is not defined // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does not by
         accident trigger a request to /favicon.ico which might change the application
         state. -->
    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 139675388729168,
          CONSOLE_MODE = false,
          EVALEX = true,
          SECRET = "DfD2D4K1HnnJZqIX2OFd";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>NameError</h1>
<div class="detail">
  <p class="errormsg">NameError: global name 'app_id' is not defined</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  
  <ul><li><div class="frame" id="frame-139675388728272">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1836</em>,
      in <code class="function">__call__</code></h4>
  <pre>return self.wsgi_app(environ, start_response)</pre>
</div>

<li><div class="frame" id="frame-139675388728144">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1820</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.make_response(self.handle_exception(e))</pre>
</div>

<li><div class="frame" id="frame-139675388728528">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1403</em>,
      in <code class="function">handle_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-139675388728464">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1817</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.full_dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-139675388729616">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1477</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.handle_user_exception(e)</pre>
</div>

<li><div class="frame" id="frame-139675388729424">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1381</em>,
      in <code class="function">handle_user_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-139675388728848">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1475</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-139675388729104">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1461</em>,
      in <code class="function">dispatch_request</code></h4>
  <pre>return self.view_functions[rule.endpoint](**req.view_args)</pre>
</div>

<li><div class="frame" id="frame-139675388729296">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py"</cite>,
      line <em class="line">637</em>,
      in <code class="function">wrapped_function</code></h4>
  <pre>resp = fk.make_response(f(*args, **kwargs))</pre>
</div>

<li><div class="frame" id="frame-139675388728976">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py"</cite>,
      line <em class="line">2406</em>,
      in <code class="function">admin_message_update</code></h4>
  <pre>message = MessageModel.objects.with_id(app_id)</pre>
</div>
</ul>
  <blockquote>NameError: global name 'app_id' is not defined</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 2406, in admin_message_update
    message = MessageModel.objects.with_id(app_id)
NameError: global name 'app_id' is not defined</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 2406, in admin_message_update
    message = MessageModel.objects.with_id(app_id)
NameError: global name 'app_id' is not defined

-->

{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "This is just a test message from user2.",
        "created": "2015-12-17 21:19:06.110000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e7",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Test message"
    },
    "title": "Message 567326ca9f9d5114f35257e7"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "It is user 1 and i was wondering if you had any record on some DFT simulations.Thanks, User1",
        "created": "2015-12-17 21:19:06.098000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e1",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Hello User2"
    },
    "title": "Message 567326ca9f9d5114f35257e1"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "Hi user1, I am sorry but i currently do not have any exemple with some DFT simulations. Are you interested into collaborating in one? Thank you, User2",
        "created": "2015-12-17 21:19:06.104000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e4",
        "receiver": "56731c3a9f9d5110105a27f1",
        "sender": "56731c3a9f9d5110105a27f4",
        "title": "Duplicated - Re - Hello User2"
    },
    "title": "Message 567326ca9f9d5114f35257e4"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "This is just a test message from user2.",
        "created": "2015-12-17 21:19:06.110000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e7",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Test message"
    },
    "title": "Message 567326ca9f9d5114f35257e7"
}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>ValidationError: u'f84375c011876a6f2e8721de682f2781cc4b85f76e9d305cae33564e07b6f275' is not a valid ObjectId, it must be a 12-byte input of type 'str' or a 24-character hex string // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does not by
         accident trigger a request to /favicon.ico which might change the application
         state. -->
    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 140290172461712,
          CONSOLE_MODE = false,
          EVALEX = true,
          SECRET = "oO5KhLRu8k90cLoH95WX";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>mongoengine.errors.ValidationError</h1>
<div class="detail">
  <p class="errormsg">ValidationError: u'f84375c011876a6f2e8721de682f2781cc4b85f76e9d305cae33564e07b6f275' is not a valid ObjectId, it must be a 12-byte input of type 'str' or a 24-character hex string</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  
  <ul><li><div class="frame" id="frame-140290172461328">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1836</em>,
      in <code class="function">__call__</code></h4>
  <pre>return self.wsgi_app(environ, start_response)</pre>
</div>

<li><div class="frame" id="frame-140290172461968">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1820</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.make_response(self.handle_exception(e))</pre>
</div>

<li><div class="frame" id="frame-140290172462288">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1403</em>,
      in <code class="function">handle_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-140290172462352">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1817</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.full_dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-140290172462416">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1477</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.handle_user_exception(e)</pre>
</div>

<li><div class="frame" id="frame-140290172462480">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1381</em>,
      in <code class="function">handle_user_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-140290172462544">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1475</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-140290172462608">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1461</em>,
      in <code class="function">dispatch_request</code></h4>
  <pre>return self.view_functions[rule.endpoint](**req.view_args)</pre>
</div>

<li><div class="frame" id="frame-140290172462672">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py"</cite>,
      line <em class="line">637</em>,
      in <code class="function">wrapped_function</code></h4>
  <pre>resp = fk.make_response(f(*args, **kwargs))</pre>
</div>

<li><div class="frame" id="frame-140290172462032">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py"</cite>,
      line <em class="line">2422</em>,
      in <code class="function">admin_message_update</code></h4>
  <pre>sender = UserModel.objects.with_id(sender_id)</pre>
</div>

<li><div class="frame" id="frame-140290172462800">
  <h4>File <cite class="filename">"build/bdist.linux-x86_64/egg/mongoengine/queryset/base.py"</cite>,
      line <em class="line">554</em>,
      in <code class="function">with_id</code></h4>
  <pre>return queryset.filter(pk=object_id).first()</pre>
</div>

<li><div class="frame" id="frame-140290172462736">
  <h4>File <cite class="filename">"build/bdist.linux-x86_64/egg/mongoengine/queryset/base.py"</cite>,
      line <em class="line">273</em>,
      in <code class="function">first</code></h4>
  <pre>result = queryset[0]</pre>
</div>

<li><div class="frame" id="frame-140290172462864">
  <h4>File <cite class="filename">"build/bdist.linux-x86_64/egg/mongoengine/queryset/base.py"</cite>,
      line <em class="line">151</em>,
      in <code class="function">__getitem__</code></h4>
  <pre>return queryset._document._from_son(queryset._cursor[key],</pre>
</div>

<li><div class="frame" id="frame-140290172462928">
  <h4>File <cite class="filename">"build/bdist.linux-x86_64/egg/mongoengine/queryset/base.py"</cite>,
      line <em class="line">1267</em>,
      in <code class="function">_cursor</code></h4>
  <pre>self._cursor_obj = self._collection.find(self._query,</pre>
</div>

<li><div class="frame" id="frame-140290172462992">
  <h4>File <cite class="filename">"build/bdist.linux-x86_64/egg/mongoengine/queryset/base.py"</cite>,
      line <em class="line">1301</em>,
      in <code class="function">_query</code></h4>
  <pre>self._mongo_query = self._query_obj.to_query(self._document)</pre>
</div>

<li><div class="frame" id="frame-140290172463056">
  <h4>File <cite class="filename">"build/bdist.linux-x86_64/egg/mongoengine/queryset/visitor.py"</cite>,
      line <em class="line">93</em>,
      in <code class="function">to_query</code></h4>
  <pre>query = query.accept(QueryCompilerVisitor(document))</pre>
</div>

<li><div class="frame" id="frame-140290172463120">
  <h4>File <cite class="filename">"build/bdist.linux-x86_64/egg/mongoengine/queryset/visitor.py"</cite>,
      line <em class="line">158</em>,
      in <code class="function">accept</code></h4>
  <pre>return visitor.visit_query(self)</pre>
</div>

<li><div class="frame" id="frame-140290172463184">
  <h4>File <cite class="filename">"build/bdist.linux-x86_64/egg/mongoengine/queryset/visitor.py"</cite>,
      line <em class="line">81</em>,
      in <code class="function">visit_query</code></h4>
  <pre>return transform.query(self.document, **query.query)</pre>
</div>

<li><div class="frame" id="frame-140290172463248">
  <h4>File <cite class="filename">"build/bdist.linux-x86_64/egg/mongoengine/queryset/transform.py"</cite>,
      line <em class="line">88</em>,
      in <code class="function">query</code></h4>
  <pre>value = field.prepare_query_value(op, value)</pre>
</div>

<li><div class="frame" id="frame-140290172463312">
  <h4>File <cite class="filename">"build/bdist.linux-x86_64/egg/mongoengine/base/fields.py"</cite>,
      line <em class="line">405</em>,
      in <code class="function">prepare_query_value</code></h4>
  <pre>return self.to_mongo(value)</pre>
</div>

<li><div class="frame" id="frame-140290172463376">
  <h4>File <cite class="filename">"build/bdist.linux-x86_64/egg/mongoengine/base/fields.py"</cite>,
      line <em class="line">401</em>,
      in <code class="function">to_mongo</code></h4>
  <pre>self.error(unicode(e))</pre>
</div>

<li><div class="frame" id="frame-140290172463440">
  <h4>File <cite class="filename">"build/bdist.linux-x86_64/egg/mongoengine/base/fields.py"</cite>,
      line <em class="line">124</em>,
      in <code class="function">error</code></h4>
  <pre>raise ValidationError(message, errors=errors, field_name=field_name)</pre>
</div>
</ul>
  <blockquote>ValidationError: u'f84375c011876a6f2e8721de682f2781cc4b85f76e9d305cae33564e07b6f275' is not a valid ObjectId, it must be a 12-byte input of type 'str' or a 24-character hex string</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 2422, in admin_message_update
    sender = UserModel.objects.with_id(sender_id)
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/base.py", line 554, in with_id
    return queryset.filter(pk=object_id).first()
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/base.py", line 273, in first
    result = queryset[0]
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/base.py", line 151, in __getitem__
    return queryset._document._from_son(queryset._cursor[key],
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/base.py", line 1267, in _cursor
    self._cursor_obj = self._collection.find(self._query,
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/base.py", line 1301, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/visitor.py", line 93, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/visitor.py", line 158, in accept
    return visitor.visit_query(self)
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/visitor.py", line 81, in visit_query
    return transform.query(self.document, **query.query)
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/transform.py", line 88, in query
    value = field.prepare_query_value(op, value)
  File "build/bdist.linux-x86_64/egg/mongoengine/base/fields.py", line 405, in prepare_query_value
    return self.to_mongo(value)
  File "build/bdist.linux-x86_64/egg/mongoengine/base/fields.py", line 401, in to_mongo
    self.error(unicode(e))
  File "build/bdist.linux-x86_64/egg/mongoengine/base/fields.py", line 124, in error
    raise ValidationError(message, errors=errors, field_name=field_name)
ValidationError: u'f84375c011876a6f2e8721de682f2781cc4b85f76e9d305cae33564e07b6f275' is not a valid ObjectId, it must be a 12-byte input of type 'str' or a 24-character hex string</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 2422, in admin_message_update
    sender = UserModel.objects.with_id(sender_id)
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/base.py", line 554, in with_id
    return queryset.filter(pk=object_id).first()
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/base.py", line 273, in first
    result = queryset[0]
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/base.py", line 151, in __getitem__
    return queryset._document._from_son(queryset._cursor[key],
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/base.py", line 1267, in _cursor
    self._cursor_obj = self._collection.find(self._query,
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/base.py", line 1301, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/visitor.py", line 93, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/visitor.py", line 158, in accept
    return visitor.visit_query(self)
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/visitor.py", line 81, in visit_query
    return transform.query(self.document, **query.query)
  File "build/bdist.linux-x86_64/egg/mongoengine/queryset/transform.py", line 88, in query
    value = field.prepare_query_value(op, value)
  File "build/bdist.linux-x86_64/egg/mongoengine/base/fields.py", line 405, in prepare_query_value
    return self.to_mongo(value)
  File "build/bdist.linux-x86_64/egg/mongoengine/base/fields.py", line 401, in to_mongo
    self.error(unicode(e))
  File "build/bdist.linux-x86_64/egg/mongoengine/base/fields.py", line 124, in error
    raise ValidationError(message, errors=errors, field_name=field_name)
ValidationError: u'f84375c011876a6f2e8721de682f2781cc4b85f76e9d305cae33564e07b6f275' is not a valid ObjectId, it must be a 12-byte input of type 'str' or a 24-character hex string

-->

{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "This is just a test message from user2.",
        "created": "2015-12-17 21:19:06.110000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e7",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Test message"
    },
    "title": "Message 567326ca9f9d5114f35257e7"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "It is user 1 and i was wondering if you had any record on some DFT simulations.Thanks, User1",
        "created": "2015-12-17 21:19:06.098000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e1",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Hello User2"
    },
    "title": "Message 567326ca9f9d5114f35257e1"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "Hi user1, I am sorry but i currently do not have any exemple with some DFT simulations. Are you interested into collaborating in one? Thank you, User2",
        "created": "2015-12-17 21:19:06.104000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e4",
        "receiver": "56731c3a9f9d5110105a27f1",
        "sender": "56731c3a9f9d5110105a27f4",
        "title": "Duplicated - Re - Hello User2"
    },
    "title": "Message 567326ca9f9d5114f35257e4"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "This is just a test message from user2.",
        "created": "2015-12-17 21:19:06.110000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e7",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Test message"
    },
    "title": "Message 567326ca9f9d5114f35257e7"
}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>NameError: global name 'name' is not defined // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does not by
         accident trigger a request to /favicon.ico which might change the application
         state. -->
    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 140105499109520,
          CONSOLE_MODE = false,
          EVALEX = true,
          SECRET = "ZytF8dQq7mqZfF4YZ90e";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>NameError</h1>
<div class="detail">
  <p class="errormsg">NameError: global name 'name' is not defined</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  
  <ul><li><div class="frame" id="frame-140105499109904">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1836</em>,
      in <code class="function">__call__</code></h4>
  <pre>return self.wsgi_app(environ, start_response)</pre>
</div>

<li><div class="frame" id="frame-140105499108368">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1820</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.make_response(self.handle_exception(e))</pre>
</div>

<li><div class="frame" id="frame-140105499109456">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1403</em>,
      in <code class="function">handle_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-140105499109264">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1817</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.full_dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-140105499108304">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1477</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.handle_user_exception(e)</pre>
</div>

<li><div class="frame" id="frame-140105499110736">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1381</em>,
      in <code class="function">handle_user_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-140105499110864">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1475</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-140105499108048">
  <h4>File <cite class="filename">"/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1461</em>,
      in <code class="function">dispatch_request</code></h4>
  <pre>return self.view_functions[rule.endpoint](**req.view_args)</pre>
</div>

<li><div class="frame" id="frame-140105499275792">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py"</cite>,
      line <em class="line">637</em>,
      in <code class="function">wrapped_function</code></h4>
  <pre>resp = fk.make_response(f(*args, **kwargs))</pre>
</div>

<li><div class="frame" id="frame-140105499276432">
  <h4>File <cite class="filename">"/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py"</cite>,
      line <em class="line">2433</em>,
      in <code class="function">admin_message_update</code></h4>
  <pre>message.title = name</pre>
</div>
</ul>
  <blockquote>NameError: global name 'name' is not defined</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 2433, in admin_message_update
    message.title = name
NameError: global name 'name' is not defined</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fyc/anaconda/envs/corr-api/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/__init__.py", line 637, in wrapped_function
    resp = fk.make_response(f(*args, **kwargs))
  File "/home/fyc/Documents/Projects/NIST/CoRR/github/corr-api/api/endpoints/admin_api.py", line 2433, in admin_message_update
    message.title = name
NameError: global name 'name' is not defined

-->

{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "This is just a test message from user2.",
        "created": "2015-12-17 21:19:06.110000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e7",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Test message"
    },
    "title": "Message 567326ca9f9d5114f35257e7"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "It is user 1 and i was wondering if you had any record on some DFT simulations.Thanks, User1",
        "created": "2015-12-17 21:19:06.098000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e1",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Hello User2"
    },
    "title": "Message 567326ca9f9d5114f35257e1"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "Hi user1, I am sorry but i currently do not have any exemple with some DFT simulations. Are you interested into collaborating in one? Thank you, User2",
        "created": "2015-12-17 21:19:06.104000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e4",
        "receiver": "56731c3a9f9d5110105a27f1",
        "sender": "56731c3a9f9d5110105a27f4",
        "title": "Duplicated - Re - Hello User2"
    },
    "title": "Message 567326ca9f9d5114f35257e4"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "This is just a test message from user2.",
        "created": "2015-12-17 21:19:06.110000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e7",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Duplicated - Test message"
    },
    "title": "Message 567326ca9f9d5114f35257e7"
}
{
    "code": 201,
    "content": {
        "attachments": 0,
        "created": "2015-12-17 21:19:06.110000",
        "id": "567326ca9f9d5114f35257e7",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Your impressions about this platform."
    },
    "title": "Message updated"
}
{
    "code": 200,
    "content": {
        "attachments": [],
        "content": "What do you think about CoRR?",
        "created": "2015-12-17 21:19:06.110000",
        "extend": {},
        "id": "567326ca9f9d5114f35257e7",
        "receiver": "56731c3a9f9d5110105a27f4",
        "sender": "56731c3a9f9d5110105a27f1",
        "title": "Your impressions about this platform."
    },
    "title": "Message 567326ca9f9d5114f35257e7"
}
